var SpreadsheetData = [
    {
        "Alias": "Hannah Abbott",
        "Major": "Graphic Design",
        "Visualization": 4,
        "Drawing": 4,
        "Programming": 4,
        "Graphics": 6,
        "HCIProgramming": 4,
        "Evaluation": 3,
        "Hobbies": "Friendly and approachable. Have an easy time for understanding smaller details. Game Design have been my specific interest for the last few years, have done a bit of game dev myself. My main hobbies (outside of game dev) at the moment are acting and dancing."
    },
    {
        "Alias": "Ludo Bagman",
        "Major": "Information and Network Engineering (mention in Multimedia Analysis)",
        "Visualization": 4,
        "Drawing": 4,
        "Programming": 6,
        "Graphics": 4,
        "HCIProgramming": 4,
        "Evaluation": 1,
        "Hobbies": "My main general interest is music. Recently I have been reading a book with a lot of data representations and it reminded me that data visualization is something I would like to learn more about (also because I like design). My main technical interest is multimedia processing because I like applied maths and multimedia analysis (originally I started my bachelor because of audio, but now I actually prefer image)."
    },
    {
        "Alias": "Bathilda Bagshot",
        "Major": "Computer Science, Human-Computer Interaction, Media Technology",
        "Visualization": 3,
        "Drawing": 4,
        "Programming": 6,
        "Graphics": 1,
        "HCIProgramming": 4,
        "Evaluation": 3,
        "Hobbies": "Travel, admire landscapes, photography, understand mass and companies market choices (e.g. The real reasons why Instagram hides \"likes\" number on its app, thy people love a certain brand and what it gives to them), UI design, understand user needs and experience, slow reading, free climbing, play electric bass guitar, manage a summer camp and be involved as an entertainer."
    },
    {
        "Alias": "Katie Bell",
        "Major": "Computer Science",
        "Visualization": 8,
        "Drawing": 6,
        "Programming": 10,
        "Graphics": 5,
        "HCIProgramming": 5,
        "Evaluation": 4,
        "Hobbies": "I've been a software developer for about 12 years, and I'm looking to make a career change into more research related work. I am also a martial artist and an (almost) certified martial arts instructor, and a mediocre bass and guitar player."
    },
    {
        "Alias": "Cuthbert Binns",
        "Major": "Computer Science",
        "Visualization": 6,
        "Drawing": 4,
        "Programming": 8,
        "Graphics": 8,
        "HCIProgramming": 6,
        "Evaluation": 4,
        "Hobbies": "Gaming, Reddit, Instagram, CrossFit"
    },
    {
        "Alias": "Phineas Nigellus Black",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 1,
        "Programming": 7,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 4,
        "Hobbies": "Movies, music, gym (going to the supermarket)"
    },
    {
        "Alias": "Sirius Black",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 4,
        "Programming": 4,
        "Graphics": 1,
        "HCIProgramming": 2,
        "Evaluation": 3,
        "Hobbies": "Movies, games, cooking"
    },
    {
        "Alias": "Amelia Bones",
        "Major": "Human-Computer Interaction, Media Technology",
        "Visualization": 5,
        "Drawing": 2,
        "Programming": 4,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 4,
        "Hobbies": "I love playing computer games my favorite game is Cities skyline, close followed by Dota 2. I love UX-design, and smart solutions within the design. I wish I was the one who invented the green button on the phone when you want to call some one. I have worked mostly with web pages and apps. I also work part time for the Sas Scandinavian Airlines were I help them gater and present data from there big database in a way that makes sense and can easily be understood and I love it. My main tool at work is power bi, sql and excel"
    },
    {
        "Alias": "Susan Bones",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 5,
        "Programming": 6,
        "Graphics": 3,
        "HCIProgramming": 5,
        "Evaluation": 4,
        "Hobbies": "Sports, stock, software development, business"
    },
    {
        "Alias": "Terry Boot",
        "Major": "Computer Science",
        "Visualization": 1,
        "Drawing": 7,
        "Programming": 6,
        "Graphics": 1,
        "HCIProgramming": 4,
        "Evaluation": 3,
        "Hobbies": "Game development"
    },
    {
        "Alias": "Lavender Brown",
        "Major": "Human-Computer Interaction, Media Technology",
        "Visualization": 2,
        "Drawing": 5,
        "Programming": 5,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 2,
        "Hobbies": "I like to program in general, especially front end. On my spare time I go to the gym and hang with friends."
    },
    {
        "Alias": "Millicent Bulstrode",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 5,
        "Programming": 2,
        "Graphics": 4,
        "HCIProgramming": 3,
        "Evaluation": 4,
        "Hobbies": "My main interest is music, as a hobby I regularly play with a swing orchestra. I'm also interested in how far technology can reach in making people interact with it and how people can interact among themselves using technology, hence my decisione to join a interactive technology related faculty."
    },
    {
        "Alias": "Charity Burbage",
        "Major": "Media Technology",
        "Visualization": 5,
        "Drawing": 8,
        "Programming": 7,
        "Graphics": 1,
        "HCIProgramming": 4,
        "Evaluation": 4,
        "Hobbies": "I like painting with oil and acrylics. I work as an app developer but Will finish my masters anyway. The app I am working with is mostly about visualising data, with d3 for instance. Looking forward to become better at it"
    },
    {
        "Alias": "Frank Bryce",
        "Major": "Human-Computer Interaction, Media Technology",
        "Visualization": 2,
        "Drawing": 1,
        "Programming": 5,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 3,
        "Hobbies": "I like programming especially front-end!"
    },
    {
        "Alias": "Alecto Carrow",
        "Major": "Computer Science",
        "Visualization": 4,
        "Drawing": 4,
        "Programming": 7,
        "Graphics": 5,
        "HCIProgramming": 4,
        "Evaluation": 3,
        "Hobbies": "Game development, figure skating, playing games"
    },
    {
        "Alias": "Amycus Carrow",
        "Major": "Computer Science",
        "Visualization": 5,
        "Drawing": 9,
        "Programming": 5,
        "Graphics": 5,
        "HCIProgramming": 5,
        "Evaluation": 5,
        "Hobbies": "I like art, painting, drawing and work with Photoshop in my spare time. I want to learn more programming, especially JavaScript at the moment."
    },
    {
        "Alias": "Reginald Cattermole",
        "Major": "Human-Computer Interaction",
        "Visualization": 2,
        "Drawing": 7,
        "Programming": 7,
        "Graphics": 6,
        "HCIProgramming": 6,
        "Evaluation": 8,
        "Hobbies": "My interests are design(in all forms and shapes) and dancing :)"
    },
    {
        "Alias": "Mary Cattermole",
        "Major": "Computer Science",
        "Visualization": 2,
        "Drawing": 1,
        "Programming": 5,
        "Graphics": 1,
        "HCIProgramming": 4,
        "Evaluation": 2,
        "Hobbies": "I like programming, especially web programming. I am also into sports and nutrition."
    },
    {
        "Alias": "Cho Chang",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 1,
        "Programming": 5,
        "Graphics": 5,
        "HCIProgramming": 5,
        "Evaluation": 3,
        "Hobbies": "Photography, kick-boxing, craft beer:)"
    },
    {
        "Alias": "Penelope Clearwater",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 4,
        "Programming": 5,
        "Graphics": 2,
        "HCIProgramming": 2,
        "Evaluation": 4,
        "Hobbies": "I like to analyse data and present them in visually interesting ways. I read books and news articles."
    },
    {
        "Alias": "Michael Corner",
        "Major": "Human-Computer Interaction, Media Technology",
        "Visualization": 2,
        "Drawing": 7,
        "Programming": 1,
        "Graphics": 1,
        "HCIProgramming": 2,
        "Evaluation": 8,
        "Hobbies": "I love to work out, eat good food and skiing, among other things. I'm mostly interested in design at a higher level, service- and concept design in relation to sustainability."
    },
    {
        "Alias": "Vincent Crabbe",
        "Major": "Human-Computer Interaction, Graphic Design",
        "Visualization": 3,
        "Drawing": 3,
        "Programming": 3,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 1,
        "Hobbies": "Fitness / Hiking / Guitar"
    },
    {
        "Alias": "Colin Creevey",
        "Major": "Mathematics, Statistics",
        "Visualization": 4,
        "Drawing": 6,
        "Programming": 5,
        "Graphics": 2,
        "HCIProgramming": 2,
        "Evaluation": 3,
        "Hobbies": "I am super interested in data and how it can be used to find underlying trends and patterns. I am also interested in environmental issues and equality questions. When it comes to hobbies I enjoy hiking and adventures in nature as well as traveling and taking care of my plants. Food is also a huge interest for me."
    },
    {
        "Alias": "Fleur Delacour",
        "Major": "Computer Science",
        "Visualization": 2,
        "Drawing": 9,
        "Programming": 8,
        "Graphics": 4,
        "HCIProgramming": 9,
        "Evaluation": 8,
        "Hobbies": "Interested in making computer games."
    },
    {
        "Alias": "Amos Diggory",
        "Major": "Visual Computing",
        "Visualization": 6,
        "Drawing": 1,
        "Programming": 7,
        "Graphics": 8,
        "HCIProgramming": 7,
        "Evaluation": 9,
        "Hobbies": "movies & tv, travelling, geography, science, art"
    },
    {
        "Alias": "Albus Dumbledore",
        "Major": "Media Technology",
        "Visualization": 5,
        "Drawing": 1,
        "Programming": 5,
        "Graphics": 1,
        "HCIProgramming": 5,
        "Evaluation": 7,
        "Hobbies": "My main interests outside of school are cooking, music (consuming, I'm not talented enough to create), and reading. I occasionally play video games or exercise, but they're not really \"passions"
    },
    {
        "Alias": "Seamus Finnigan",
        "Major": "Computer Science",
        "Visualization": 3,
        "Drawing": 3,
        "Programming": 7,
        "Graphics": 2,
        "HCIProgramming": 4,
        "Evaluation": 2,
        "Hobbies": "I'm interested in pretty much everything relating to the brain, cognition, and consciousness: neuroscience, philosophy, psychology, information technology. I spend most of my free time on nurturing these interests. I also like to listen to a lot of music (mostly hip hop) and sometimes play the piano."
    },
    {
        "Alias": "Marcus Flint",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 8,
        "Programming": 4,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 2,
        "Hobbies": "From a career perspective, I am interested in UX design and frontend development. Art is a hobby."
    },
    {
        "Alias": "Filius Flitwick",
        "Major": "Computer Science",
        "Visualization": 5,
        "Drawing": 6,
        "Programming": 8,
        "Graphics": 5,
        "HCIProgramming": 7,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Cornelius Fudge",
        "Major": "Computer Science",
        "Visualization": 1,
        "Drawing": 3,
        "Programming": 7,
        "Graphics": 3,
        "HCIProgramming": 1,
        "Evaluation": 1,
        "Hobbies": ""
    },
    {
        "Alias": "Gellert Grindelwald",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 8,
        "Programming": 3,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 3,
        "Hobbies": ""
    },
    {
        "Alias": "Godric Gryffindor",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 6,
        "Programming": 5,
        "Graphics": 3,
        "HCIProgramming": 2,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Rubeus Hagrid",
        "Major": "Computer Science, Transport Science/Systems",
        "Visualization": 6,
        "Drawing": 6,
        "Programming": 7,
        "Graphics": 4,
        "HCIProgramming": 4,
        "Evaluation": 2,
        "Hobbies": ""
    },
    {
        "Alias": "Rolanda Hooch",
        "Major": "Computer Science",
        "Visualization": 5,
        "Drawing": 5,
        "Programming": 6,
        "Graphics": 2,
        "HCIProgramming": 4,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Helga Hufflepuff",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 3,
        "Programming": 6,
        "Graphics": 2,
        "HCIProgramming": 6,
        "Evaluation": 5,
        "Hobbies": ""
    },
    {
        "Alias": "Hermione Granger",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 1,
        "Programming": 4,
        "Graphics": 2,
        "HCIProgramming": 5,
        "Evaluation": 8,
        "Hobbies": ""
    },
    {
        "Alias": "Igor Karkaroff",
        "Major": "Computer Science",
        "Visualization": 1,
        "Drawing": 6,
        "Programming": 6,
        "Graphics": 1,
        "HCIProgramming": 1,
        "Evaluation": 4,
        "Hobbies": ""
    },
    {
        "Alias": "Viktor Krum",
        "Major": "Media Technology",
        "Visualization": 6,
        "Drawing": 6,
        "Programming": 7,
        "Graphics": 4,
        "HCIProgramming": 4,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Silvanus Kettleburn",
        "Major": "Media Technology, ICT",
        "Visualization": 4,
        "Drawing": 5,
        "Programming": 4,
        "Graphics": 2,
        "HCIProgramming": 2,
        "Evaluation": 5,
        "Hobbies": ""
    },
    {
        "Alias": "Bellatrix Lestrange",
        "Major": "Human-Computer Interaction",
        "Visualization": 5,
        "Drawing": 6,
        "Programming": 2,
        "Graphics": 2,
        "HCIProgramming": 3,
        "Evaluation": 4,
        "Hobbies": ""
    },
    {
        "Alias": "Neville Longbottom",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 5,
        "Programming": 5,
        "Graphics": 5,
        "HCIProgramming": 5,
        "Evaluation": 4,
        "Hobbies": ""
    },
    {
        "Alias": "Xenophilius Lovegood",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 5,
        "Programming": 8,
        "Graphics": 2,
        "HCIProgramming": 4,
        "Evaluation": 5,
        "Hobbies": ""
    },
    {
        "Alias": "Remus Lupin",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 6,
        "Programming": 6,
        "Graphics": 4,
        "HCIProgramming": 8,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Draco Malfoy",
        "Major": "Media Technology",
        "Visualization": 8,
        "Drawing": 5,
        "Programming": 7,
        "Graphics": 5,
        "HCIProgramming": 6,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Ernie Macmillan",
        "Major": "Human-Computer Interaction",
        "Visualization": 3,
        "Drawing": 1,
        "Programming": 10,
        "Graphics": 2,
        "HCIProgramming": 1,
        "Evaluation": 8,
        "Hobbies": ""
    },
    {
        "Alias": "Minerva McGonagall",
        "Major": "Media Technology",
        "Visualization": 7,
        "Drawing": 8,
        "Programming": 6,
        "Graphics": 4,
        "HCIProgramming": 7,
        "Evaluation": 8,
        "Hobbies": ""
    },
    {
        "Alias": "Cormac McLaggen",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 3,
        "Programming": 2,
        "Graphics": 1,
        "HCIProgramming": 1,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Graham Montague",
        "Major": "Graphic Design, Product Design",
        "Visualization": 3,
        "Drawing": 8,
        "Programming": 2,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Theodore Nott",
        "Major": "Computer Science",
        "Visualization": 4,
        "Drawing": 8,
        "Programming": 6,
        "Graphics": 4,
        "HCIProgramming": 4,
        "Evaluation": 3,
        "Hobbies": ""
    },
    {
        "Alias": "Garrick Ollivander",
        "Major": "Media Technology",
        "Visualization": 1,
        "Drawing": 3,
        "Programming": 5,
        "Graphics": 1,
        "HCIProgramming": 2,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Pansy Parkinson",
        "Major": "Media Technology",
        "Visualization": 8,
        "Drawing": 7,
        "Programming": 8,
        "Graphics": 8,
        "HCIProgramming": 6,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Peter Pettigrew",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 2,
        "Programming": 3,
        "Graphics": 3,
        "HCIProgramming": 3,
        "Evaluation": 8,
        "Hobbies": ""
    },
    {
        "Alias": "Antioch Peverell",
        "Major": "Media Technology",
        "Visualization": 1,
        "Drawing": 5,
        "Programming": 1,
        "Graphics": 1,
        "HCIProgramming": 1,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Irma Pince",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 10,
        "Programming": 3,
        "Graphics": 1,
        "HCIProgramming": 3,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Sturgis Podmore",
        "Major": "Media Technology",
        "Visualization": 2,
        "Drawing": 3,
        "Programming": 1,
        "Graphics": 1,
        "HCIProgramming": 2,
        "Evaluation": 3,
        "Hobbies": ""
    },
    {
        "Alias": "Poppy Pomfrey",
        "Major": "Computer Science",
        "Visualization": 5,
        "Drawing": 3,
        "Programming": 7,
        "Graphics": 3,
        "HCIProgramming": 4,
        "Evaluation": 4,
        "Hobbies": ""
    },
    {
        "Alias": "Harry Potter",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 2,
        "Programming": 2,
        "Graphics": 3,
        "HCIProgramming": 3,
        "Evaluation": 3,
        "Hobbies": ""
    },
    {
        "Alias": "James Potter",
        "Major": "Human-Computer Interaction",
        "Visualization": 4,
        "Drawing": 8,
        "Programming": 1,
        "Graphics": 3,
        "HCIProgramming": 4,
        "Evaluation": 8,
        "Hobbies": ""
    },
    {
        "Alias": "Lily Potter",
        "Major": "Media Technology",
        "Visualization": 4,
        "Drawing": 6,
        "Programming": 3,
        "Graphics": 4,
        "HCIProgramming": 4,
        "Evaluation": 7,
        "Hobbies": ""
    },
    {
        "Alias": "Quirinus Quirrell",
        "Major": "Computer Science",
        "Visualization": 6,
        "Drawing": 8,
        "Programming": 7,
        "Graphics": 7,
        "HCIProgramming": 7,
        "Evaluation": 3,
        "Hobbies": ""
    },
    {
        "Alias": "Helena Ravenclaw",
        "Major": "Computer Science",
        "Visualization": 7,
        "Drawing": 8,
        "Programming": 5,
        "Graphics": 5,
        "HCIProgramming": 6,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Rowena Ravenclaw",
        "Major": "Computer Science",
        "Visualization": 6,
        "Drawing": 5,
        "Programming": 6,
        "Graphics": 2,
        "HCIProgramming": 6,
        "Evaluation": 6,
        "Hobbies": ""
    },
    {
        "Alias": "Tom Marvolo Riddle",
        "Major": "Media Technology",
        "Visualization": 3,
        "Drawing": 5,
        "Programming": 5,
        "Graphics": 2,
        "HCIProgramming": 3,
        "Evaluation": 5,
        "Hobbies": ""
    },
    {
        "Alias": "Demelza Robins",
        "Major": "Computer Science",
        "Visualization": 3,
        "Drawing": 4,
        "Programming": 7,
        "Graphics": 5,
        "HCIProgramming": 5,
        "Evaluation": 5,
        "Hobbies": ""
    }
];

let dataArr = [];
SpreadsheetData.forEach(element => {
    dataArr.push({
        'VisualizationSkills': element.Visualization,
        'DrawingSkills': element.Drawing,
        'ProgrammingSkills': element.Programming,
        'GraphicsSkills': element.Graphics,
        'HCISkills': element.HCIProgramming,
        'EvalSkills': element.Evaluation,
        'Alias': element.Alias,
        'Hobbies': element.Hobbies
    }
    );
});

export default SpreadsheetData;
export { dataArr };